#!/bin/bash

psql << EOF
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;

CREATE USER '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_PASS';
CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASS';
GRANT ALL ON *.* TO '$MYSQL_USER'@'localhost';
GRANT ALL ON *.* TO '$MYSQL_USER'@'%';
FLUSH PRIVILEGES;
###WHERE MYUSER AND MYPASS IS HIDDEN FROM ENV from SECRETS!

EOF

